// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: proto/handler_bridge.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceId string            `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId  string            `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Tenant  string            `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Baggage map[string]string `protobuf:"bytes,4,rep,name=baggage,proto3" json:"baggage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Meta) Reset() {
	*x = Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *Meta) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Meta) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Meta) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Meta) GetBaggage() map[string]string {
	if x != nil {
		return x.Baggage
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details []byte `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Status) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to V:
	//
	//	*Value_S
	//	*Value_I64
	//	*Value_F64
	//	*Value_B
	//	*Value_Bin
	//	*Value_Json
	V isValue_V `protobuf_oneof:"v"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{2}
}

func (m *Value) GetV() isValue_V {
	if m != nil {
		return m.V
	}
	return nil
}

func (x *Value) GetS() string {
	if x, ok := x.GetV().(*Value_S); ok {
		return x.S
	}
	return ""
}

func (x *Value) GetI64() int64 {
	if x, ok := x.GetV().(*Value_I64); ok {
		return x.I64
	}
	return 0
}

func (x *Value) GetF64() float64 {
	if x, ok := x.GetV().(*Value_F64); ok {
		return x.F64
	}
	return 0
}

func (x *Value) GetB() bool {
	if x, ok := x.GetV().(*Value_B); ok {
		return x.B
	}
	return false
}

func (x *Value) GetBin() []byte {
	if x, ok := x.GetV().(*Value_Bin); ok {
		return x.Bin
	}
	return nil
}

func (x *Value) GetJson() string {
	if x, ok := x.GetV().(*Value_Json); ok {
		return x.Json
	}
	return ""
}

type isValue_V interface {
	isValue_V()
}

type Value_S struct {
	S string `protobuf:"bytes,1,opt,name=s,proto3,oneof"`
}

type Value_I64 struct {
	I64 int64 `protobuf:"varint,2,opt,name=i64,proto3,oneof"`
}

type Value_F64 struct {
	F64 float64 `protobuf:"fixed64,3,opt,name=f64,proto3,oneof"`
}

type Value_B struct {
	B bool `protobuf:"varint,4,opt,name=b,proto3,oneof"`
}

type Value_Bin struct {
	Bin []byte `protobuf:"bytes,5,opt,name=bin,proto3,oneof"`
}

type Value_Json struct {
	Json string `protobuf:"bytes,6,opt,name=json,proto3,oneof"`
}

func (*Value_S) isValue_V() {}

func (*Value_I64) isValue_V() {}

func (*Value_F64) isValue_V() {}

func (*Value_B) isValue_V() {}

func (*Value_Bin) isValue_V() {}

func (*Value_Json) isValue_V() {}

type InvokeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandlerName string            `protobuf:"bytes,1,opt,name=handler_name,json=handlerName,proto3" json:"handler_name,omitempty"`
	Method      string            `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Correlation string            `protobuf:"bytes,3,opt,name=correlation,proto3" json:"correlation,omitempty"`
	Meta        *Meta             `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	Input       map[string]*Value `protobuf:"bytes,5,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeRequest) GetHandlerName() string {
	if x != nil {
		return x.HandlerName
	}
	return ""
}

func (x *InvokeRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InvokeRequest) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

func (x *InvokeRequest) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *InvokeRequest) GetInput() map[string]*Value {
	if x != nil {
		return x.Input
	}
	return nil
}

type InvokeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Correlation string            `protobuf:"bytes,1,opt,name=correlation,proto3" json:"correlation,omitempty"`
	Status      *Status           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Output      map[string]*Value `protobuf:"bytes,3,rep,name=output,proto3" json:"output,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *InvokeResponse) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

func (x *InvokeResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *InvokeResponse) GetOutput() map[string]*Value {
	if x != nil {
		return x.Output
	}
	return nil
}

type LogReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level  string            `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Msg    string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Fields map[string]*Value `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *LogReq) Reset() {
	*x = LogReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogReq) ProtoMessage() {}

func (x *LogReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogReq.ProtoReflect.Descriptor instead.
func (*LogReq) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *LogReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LogReq) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type EmitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string            `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data  map[string]*Value `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *EmitReq) Reset() {
	*x = EmitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitReq) ProtoMessage() {}

func (x *EmitReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitReq.ProtoReflect.Descriptor instead.
func (*EmitReq) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *EmitReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EmitReq) GetData() map[string]*Value {
	if x != nil {
		return x.Data
	}
	return nil
}

type KVGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *KVGetReq) Reset() {
	*x = KVGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVGetReq) ProtoMessage() {}

func (x *KVGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVGetReq.ProtoReflect.Descriptor instead.
func (*KVGetReq) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *KVGetReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *KVGetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVPutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value  *Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	TtlSec int64  `protobuf:"varint,4,opt,name=ttl_sec,json=ttlSec,proto3" json:"ttl_sec,omitempty"`
}

func (x *KVPutReq) Reset() {
	*x = KVPutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVPutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPutReq) ProtoMessage() {}

func (x *KVPutReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPutReq.ProtoReflect.Descriptor instead.
func (*KVPutReq) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *KVPutReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *KVPutReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVPutReq) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KVPutReq) GetTtlSec() int64 {
	if x != nil {
		return x.TtlSec
	}
	return 0
}

type KVDelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *KVDelReq) Reset() {
	*x = KVDelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVDelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDelReq) ProtoMessage() {}

func (x *KVDelReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDelReq.ProtoReflect.Descriptor instead.
func (*KVDelReq) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *KVDelReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *KVDelReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Value  *Value  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KVGetRes) Reset() {
	*x = KVGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVGetRes) ProtoMessage() {}

func (x *KVGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVGetRes.ProtoReflect.Descriptor instead.
func (*KVGetRes) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *KVGetRes) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *KVGetRes) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type KVCommonRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *KVCommonRes) Reset() {
	*x = KVCommonRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVCommonRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVCommonRes) ProtoMessage() {}

func (x *KVCommonRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVCommonRes.ProtoReflect.Descriptor instead.
func (*KVCommonRes) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *KVCommonRes) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnixMs int64  `protobuf:"varint,1,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	Note   string `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *Heartbeat) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

func (x *Heartbeat) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type Control struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Correlation string `protobuf:"bytes,1,opt,name=correlation,proto3" json:"correlation,omitempty"`
	Meta        *Meta  `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	// Types that are assignable to OneofMsg:
	//
	//	*Control_Log
	//	*Control_Emit
	//	*Control_KvGet
	//	*Control_KvPut
	//	*Control_KvDel
	//	*Control_KvGetRes
	//	*Control_KvCommonRes
	//	*Control_Heartbeat
	OneofMsg isControl_OneofMsg `protobuf_oneof:"oneof_msg"`
}

func (x *Control) Reset() {
	*x = Control{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_handler_bridge_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_proto_handler_bridge_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_proto_handler_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *Control) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

func (x *Control) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (m *Control) GetOneofMsg() isControl_OneofMsg {
	if m != nil {
		return m.OneofMsg
	}
	return nil
}

func (x *Control) GetLog() *LogReq {
	if x, ok := x.GetOneofMsg().(*Control_Log); ok {
		return x.Log
	}
	return nil
}

func (x *Control) GetEmit() *EmitReq {
	if x, ok := x.GetOneofMsg().(*Control_Emit); ok {
		return x.Emit
	}
	return nil
}

func (x *Control) GetKvGet() *KVGetReq {
	if x, ok := x.GetOneofMsg().(*Control_KvGet); ok {
		return x.KvGet
	}
	return nil
}

func (x *Control) GetKvPut() *KVPutReq {
	if x, ok := x.GetOneofMsg().(*Control_KvPut); ok {
		return x.KvPut
	}
	return nil
}

func (x *Control) GetKvDel() *KVDelReq {
	if x, ok := x.GetOneofMsg().(*Control_KvDel); ok {
		return x.KvDel
	}
	return nil
}

func (x *Control) GetKvGetRes() *KVGetRes {
	if x, ok := x.GetOneofMsg().(*Control_KvGetRes); ok {
		return x.KvGetRes
	}
	return nil
}

func (x *Control) GetKvCommonRes() *KVCommonRes {
	if x, ok := x.GetOneofMsg().(*Control_KvCommonRes); ok {
		return x.KvCommonRes
	}
	return nil
}

func (x *Control) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetOneofMsg().(*Control_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

type isControl_OneofMsg interface {
	isControl_OneofMsg()
}

type Control_Log struct {
	Log *LogReq `protobuf:"bytes,10,opt,name=log,proto3,oneof"`
}

type Control_Emit struct {
	Emit *EmitReq `protobuf:"bytes,11,opt,name=emit,proto3,oneof"`
}

type Control_KvGet struct {
	KvGet *KVGetReq `protobuf:"bytes,20,opt,name=kv_get,json=kvGet,proto3,oneof"`
}

type Control_KvPut struct {
	KvPut *KVPutReq `protobuf:"bytes,21,opt,name=kv_put,json=kvPut,proto3,oneof"`
}

type Control_KvDel struct {
	KvDel *KVDelReq `protobuf:"bytes,22,opt,name=kv_del,json=kvDel,proto3,oneof"`
}

type Control_KvGetRes struct {
	KvGetRes *KVGetRes `protobuf:"bytes,30,opt,name=kv_get_res,json=kvGetRes,proto3,oneof"`
}

type Control_KvCommonRes struct {
	KvCommonRes *KVCommonRes `protobuf:"bytes,31,opt,name=kv_common_res,json=kvCommonRes,proto3,oneof"`
}

type Control_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,40,opt,name=heartbeat,proto3,oneof"`
}

func (*Control_Log) isControl_OneofMsg() {}

func (*Control_Emit) isControl_OneofMsg() {}

func (*Control_KvGet) isControl_OneofMsg() {}

func (*Control_KvPut) isControl_OneofMsg() {}

func (*Control_KvDel) isControl_OneofMsg() {}

func (*Control_KvGetRes) isControl_OneofMsg() {}

func (*Control_KvCommonRes) isControl_OneofMsg() {}

func (*Control_Heartbeat) isControl_OneofMsg() {}

var File_proto_handler_bridge_proto protoreflect.FileDescriptor

var file_proto_handler_bridge_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f,
	0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x22, 0xc3, 0x01, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x70, 0x61, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x70, 0x61, 0x6e, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x07, 0x62, 0x61, 0x67,
	0x67, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x2e, 0x42, 0x61, 0x67, 0x67, 0x61, 0x67, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x62, 0x61, 0x67, 0x67, 0x61, 0x67, 0x65, 0x1a, 0x3a,
	0x0a, 0x0c, 0x42, 0x61, 0x67, 0x67, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x50, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x7e, 0x0a, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x01, 0x73, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x36, 0x34, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x69, 0x36, 0x34, 0x12, 0x12, 0x0a, 0x03, 0x66, 0x36, 0x34,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x03, 0x66, 0x36, 0x34, 0x12, 0x0e, 0x0a,
	0x01, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x01, 0x62, 0x12, 0x12, 0x0a,
	0x03, 0x62, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x03, 0x62, 0x69,
	0x6e, 0x12, 0x14, 0x0a, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x04, 0x6a, 0x73, 0x6f, 0x6e, 0x42, 0x03, 0x0a, 0x01, 0x76, 0x22, 0x8f, 0x02, 0x0a,
	0x0d, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x72,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x72, 0x69, 0x64,
	0x67, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x36, 0x0a,
	0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x47, 0x0a, 0x0a, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xe0,
	0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3a, 0x0a, 0x06, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x1a, 0x48, 0x0a, 0x0b, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0xae, 0x01, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x32, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x4c, 0x6f,
	0x67, 0x52, 0x65, 0x71, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x48, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x96, 0x01, 0x0a, 0x07, 0x45, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x45, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x1a, 0x46, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x34, 0x0a, 0x08, 0x4b,
	0x56, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x72, 0x0a, 0x08, 0x4b, 0x56, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x74, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74,
	0x74, 0x6c, 0x53, 0x65, 0x63, 0x22, 0x34, 0x0a, 0x08, 0x4b, 0x56, 0x44, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x57, 0x0a, 0x08, 0x4b,
	0x56, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x35, 0x0a, 0x0b, 0x4b, 0x56, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x38, 0x0a, 0x09, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x6e, 0x69, 0x78,
	0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x78, 0x4d,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0xc6, 0x03, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x48, 0x00, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x12, 0x25, 0x0a, 0x04, 0x65, 0x6d, 0x69,
	0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2e, 0x45, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x04, 0x65, 0x6d, 0x69, 0x74,
	0x12, 0x29, 0x0a, 0x06, 0x6b, 0x76, 0x5f, 0x67, 0x65, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x4b, 0x56, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x48, 0x00, 0x52, 0x05, 0x6b, 0x76, 0x47, 0x65, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x6b,
	0x76, 0x5f, 0x70, 0x75, 0x74, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x2e, 0x4b, 0x56, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52,
	0x05, 0x6b, 0x76, 0x50, 0x75, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x6b, 0x76, 0x5f, 0x64, 0x65, 0x6c,
	0x18, 0x16, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e,
	0x4b, 0x56, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x48, 0x00, 0x52, 0x05, 0x6b, 0x76, 0x44, 0x65,
	0x6c, 0x12, 0x30, 0x0a, 0x0a, 0x6b, 0x76, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x18,
	0x1e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x4b,
	0x56, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x08, 0x6b, 0x76, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x0d, 0x6b, 0x76, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x5f, 0x72, 0x65, 0x73, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2e, 0x4b, 0x56, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x48,
	0x00, 0x52, 0x0b, 0x6b, 0x76, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x31,
	0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x28, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x48, 0x00, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x42, 0x0b, 0x0a, 0x09, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x5f, 0x6d, 0x73, 0x67, 0x32, 0x44,
	0x0a, 0x07, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x06, 0x49, 0x6e, 0x76,
	0x6f, 0x6b, 0x65, 0x12, 0x15, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x76,
	0x6f, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x76, 0x6f, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x32, 0x41, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50,
	0x6c, 0x61, 0x6e, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12,
	0x0f, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x1a, 0x0f, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x65, 0x77, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x2f, 0x72,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x2d, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2d, 0x67, 0x6f,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_handler_bridge_proto_rawDescOnce sync.Once
	file_proto_handler_bridge_proto_rawDescData = file_proto_handler_bridge_proto_rawDesc
)

func file_proto_handler_bridge_proto_rawDescGZIP() []byte {
	file_proto_handler_bridge_proto_rawDescOnce.Do(func() {
		file_proto_handler_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_handler_bridge_proto_rawDescData)
	})
	return file_proto_handler_bridge_proto_rawDescData
}

var file_proto_handler_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_handler_bridge_proto_goTypes = []interface{}{
	(*Meta)(nil),           // 0: bridge.Meta
	(*Status)(nil),         // 1: bridge.Status
	(*Value)(nil),          // 2: bridge.Value
	(*InvokeRequest)(nil),  // 3: bridge.InvokeRequest
	(*InvokeResponse)(nil), // 4: bridge.InvokeResponse
	(*LogReq)(nil),         // 5: bridge.LogReq
	(*EmitReq)(nil),        // 6: bridge.EmitReq
	(*KVGetReq)(nil),       // 7: bridge.KVGetReq
	(*KVPutReq)(nil),       // 8: bridge.KVPutReq
	(*KVDelReq)(nil),       // 9: bridge.KVDelReq
	(*KVGetRes)(nil),       // 10: bridge.KVGetRes
	(*KVCommonRes)(nil),    // 11: bridge.KVCommonRes
	(*Heartbeat)(nil),      // 12: bridge.Heartbeat
	(*Control)(nil),        // 13: bridge.Control
	nil,                    // 14: bridge.Meta.BaggageEntry
	nil,                    // 15: bridge.InvokeRequest.InputEntry
	nil,                    // 16: bridge.InvokeResponse.OutputEntry
	nil,                    // 17: bridge.LogReq.FieldsEntry
	nil,                    // 18: bridge.EmitReq.DataEntry
}
var file_proto_handler_bridge_proto_depIdxs = []int32{
	14, // 0: bridge.Meta.baggage:type_name -> bridge.Meta.BaggageEntry
	0,  // 1: bridge.InvokeRequest.meta:type_name -> bridge.Meta
	15, // 2: bridge.InvokeRequest.input:type_name -> bridge.InvokeRequest.InputEntry
	1,  // 3: bridge.InvokeResponse.status:type_name -> bridge.Status
	16, // 4: bridge.InvokeResponse.output:type_name -> bridge.InvokeResponse.OutputEntry
	17, // 5: bridge.LogReq.fields:type_name -> bridge.LogReq.FieldsEntry
	18, // 6: bridge.EmitReq.data:type_name -> bridge.EmitReq.DataEntry
	2,  // 7: bridge.KVPutReq.value:type_name -> bridge.Value
	1,  // 8: bridge.KVGetRes.status:type_name -> bridge.Status
	2,  // 9: bridge.KVGetRes.value:type_name -> bridge.Value
	1,  // 10: bridge.KVCommonRes.status:type_name -> bridge.Status
	0,  // 11: bridge.Control.meta:type_name -> bridge.Meta
	5,  // 12: bridge.Control.log:type_name -> bridge.LogReq
	6,  // 13: bridge.Control.emit:type_name -> bridge.EmitReq
	7,  // 14: bridge.Control.kv_get:type_name -> bridge.KVGetReq
	8,  // 15: bridge.Control.kv_put:type_name -> bridge.KVPutReq
	9,  // 16: bridge.Control.kv_del:type_name -> bridge.KVDelReq
	10, // 17: bridge.Control.kv_get_res:type_name -> bridge.KVGetRes
	11, // 18: bridge.Control.kv_common_res:type_name -> bridge.KVCommonRes
	12, // 19: bridge.Control.heartbeat:type_name -> bridge.Heartbeat
	2,  // 20: bridge.InvokeRequest.InputEntry.value:type_name -> bridge.Value
	2,  // 21: bridge.InvokeResponse.OutputEntry.value:type_name -> bridge.Value
	2,  // 22: bridge.LogReq.FieldsEntry.value:type_name -> bridge.Value
	2,  // 23: bridge.EmitReq.DataEntry.value:type_name -> bridge.Value
	3,  // 24: bridge.Invoker.Invoke:input_type -> bridge.InvokeRequest
	13, // 25: bridge.ControlPlane.Connect:input_type -> bridge.Control
	4,  // 26: bridge.Invoker.Invoke:output_type -> bridge.InvokeResponse
	13, // 27: bridge.ControlPlane.Connect:output_type -> bridge.Control
	26, // [26:28] is the sub-list for method output_type
	24, // [24:26] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_handler_bridge_proto_init() }
func file_proto_handler_bridge_proto_init() {
	if File_proto_handler_bridge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_handler_bridge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_bridge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_bridge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_bridge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvokeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_bridge_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InvokeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_bridge_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_bridge_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_bridge_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_bridge_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVPutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_bridge_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVDelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_bridge_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_bridge_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVCommonRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_bridge_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_handler_bridge_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Control); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_handler_bridge_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Value_S)(nil),
		(*Value_I64)(nil),
		(*Value_F64)(nil),
		(*Value_B)(nil),
		(*Value_Bin)(nil),
		(*Value_Json)(nil),
	}
	file_proto_handler_bridge_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*Control_Log)(nil),
		(*Control_Emit)(nil),
		(*Control_KvGet)(nil),
		(*Control_KvPut)(nil),
		(*Control_KvDel)(nil),
		(*Control_KvGetRes)(nil),
		(*Control_KvCommonRes)(nil),
		(*Control_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_handler_bridge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_handler_bridge_proto_goTypes,
		DependencyIndexes: file_proto_handler_bridge_proto_depIdxs,
		MessageInfos:      file_proto_handler_bridge_proto_msgTypes,
	}.Build()
	File_proto_handler_bridge_proto = out.File
	file_proto_handler_bridge_proto_rawDesc = nil
	file_proto_handler_bridge_proto_goTypes = nil
	file_proto_handler_bridge_proto_depIdxs = nil
}
